## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

 - Dylan Louie: Background research, Conceptualization, Writing - original draft, Writing - review & editing

 - Ryan Rulkens: Background research, Conceptualization, Writing - original draft, Writing - review & editing

 - Shreyesh Vankina: Background research, Conceptualization, Writing - original draft, Writing - review & editing

 - Alice Lan: Conceptualization, Writing - original draft, Writing - review & editing
 
 - Annabelle Zhou: Conceptualization, Writing – original draft, Writing – review & editing

## Research Question

How does distance to the nearest university in California, total bedrooms, houses per block, and ocean proximity using the 1990 California housing dataset predict median house value, after controlling for median household income, housing age, and population density? Does distance from the nearest university in California have the strongest impact on median household income among the others, and how do these factors interact with each other to drive differences in price?

To answer this, we plan to find the Euclidean distance (in miles) between each census block and the nearest university in California using geographic coordinates. UC Merced and other universities founded post-1990 will be excluded. We will then find the archived rank of these Universities from the 1990 U.S. news College ranking and create a multi-variable regression model to estimate the relationship between these four predictors and median house value.

## Background and Prior Work

## Hypothesis

We expect that census blocks located closer to a nearby university will have higher median house values, with prices dropping steeply with distance before plateauing a few miles away due to commuting being no longer practical and the impact the distance from University makes on the local housing market being outpaced by our other variables. We also expect houses with more bedrooms and those located closer to the ocean to be associated with higher median house values. We expect a positive correlation between university proximity and housing value because campuses act as major employment and cultural hubs, while featuring large student bodies that increase demand for nearby housing. Additionally, proximity to the California coastline has historically been associated with higher housing values due to limited supply and high lifestyle demand, but this effect may not be further amplified by having a nearby university in the region as both having a University and having a nearby coastline create a similar kind of artificially inflated demand, albeit for different reasons.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name:
  - Link to the dataset:
  - Number of observations:
  - Number of variables:
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with repsect to the project
- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [4]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [5]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/COGS108/Group091_WI26/refs/heads/master/data/California_Houses.csv', 'filename':'ca_housing_1990.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress: 100%|██████████| 1/1 [00:01<00:00,  1.54s/it]

Successfully downloaded: ca_housing_1990.csv

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [6]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
houses = pd.read_csv('data/California_Houses.csv')
houses.head()

,Median_House_Value,Median_Income,Median_Age,Tot_Rooms,Tot_Bedrooms,Population,Households,Latitude,Longitude,Distance_to_coast,Distance_to_LA,Distance_to_SanDiego,Distance_to_SanJose,Distance_to_SanFrancisco
0,452600.0,8.3252,41,880,129,322,126,37.88,-122.23,9263.040773,556529.158342,735501.806984,67432.517001,21250.213767
1,358500.0,8.3014,21,7099,1106,2401,1138,37.86,-122.22,10225.733072,554279.850069,733236.884360,65049.908574,20880.600400
2,352100.0,7.2574,52,1467,190,496,177,37.85,-122.24,8259.085109,554610.717069,733525.682937,64867.289833,18811.487450
3,341300.0,5.6431,52,1274,235,558,219,37.85,-122.25,7768.086571,555194.266086,734095.290744,65287.138412,18031.047568
4,342200.0,3.8462,52,1627,280,565,259,37.85,-122.25,7768.086571,555194.266086,734095.290744,65287.138412,18031.047568

In [7]:
houses.shape

(20640, 14)

In [8]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Median_House_Value        20640 non-null  float64
 1   Median_Income             20640 non-null  float64
 2   Median_Age                20640 non-null  int64
 3   Tot_Rooms                 20640 non-null  int64
 4   Tot_Bedrooms              20640 non-null  int64
 5   Population                20640 non-null  int64
 6   Households                20640 non-null  int64
 7   Latitude                  20640 non-null  float64
 8   Longitude                 20640 non-null  float64
 9   Distance_to_coast         20640 non-null  float64
 10  Distance_to_LA            20640 non-null  float64
 11  Distance_to_SanDiego      20640 non-null  float64
 12  Distance_to_SanJose       20640 non-null  float64
 13  Distance_to_SanFrancisco  20640 non-null  float64
dtypes: float64(9), int64(5)
memory usage: 2.2 MB

### Dataset #2 

See instructions above for Dataset #1.  Feel free to keep adding as many more datasets as you need.  Put each new dataset in its own section just like these. 

Lastly if you do have multiple datasets, add another section where you demonstrate how you will join, align, cross-reference or whatever to combine data from the different datasets

Please note that you can always keep adding more datasets in the future if these datasets you turn in for the checkpoint aren't sufficient.  The goal here is demonstrate that you can obtain and wrangle data.  You are not tied down to only use what you turn in right now.

In [81]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
from bs4 import BeautifulSoup
import requests
import numpy as np
headers = {"User-Agent": "RyanRulkensBot/1.0 (ryanrulkens@gmail.com)"}
uni_data = requests.get("https://en.wikipedia.org/wiki/List_of_colleges_and_universities_in_California", headers=headers).text
soup = BeautifulSoup(uni_data)
schools = soup.find_all("tr")[2:-58]
df = []
for school in schools:
    school_data = school.find_all("td")
    if not school_data:
        continue
    if len(school_data) == 6:
        df.append({"Name": school_data[0].text[:-1], "Founding": school_data[4].text[:-1]})
    else:
        df.append({"Name": school_data[0].text[:-1], "Founding": school_data[3].text[:-1]})
school_data = pd.DataFrame(df)

defunct_university = []
du = soup.find_all('table')[5].find_all('tr')[1:]
for row in du:
    columns = row.find_all('td')
    closed = columns[3].text.strip().replace('*', '').replace('[2]', '')
    if closed == '':
        continue
    if int(closed) <= 1990:
        continue
    uni = columns[0].text.strip()
    year = columns[2].text.strip().replace('*', '')
    defunct_university.append({"Name": uni, "Founding": year})
defunct_df = pd.DataFrame(defunct_university)
school_data = pd.concat([school_data, defunct_df])
school_data["Founding"] = school_data["Founding"].apply(lambda x: x.replace("*", "").replace("---", ''))
school_data["Founding"] = school_data["Founding"].apply(lambda x: None if x == "" else int(x))
school_data = school_data[school_data["Founding"] < 1990].reset_index().drop(columns = ["index"])
school_data

                                                  Name  Founding
0                   University of California, Berkeley    1869.0
1                      University of California, Davis    1905.0
2                     University of California, Irvine    1965.0
3                University of California, Los Angeles    1882.0
4                  University of California, Riverside    1954.0
..                                                 ...       ...
142                    Marymount California University    1932.0
143                                      Mills College    1852.0
144                       National Hispanic University    1981.0
145                       Union Institute & University    1964.0
146  University of Northern California, Lorenzo Pat...    1983.0

[147 rows x 2 columns]

In [82]:
url = "https://www.mapquestapi.com/geocoding/v1/address"
lat_data = []
long_data = []
for university in school_data["Name"]:
    params = {"key": "kH8UIQ6xBOIYz0ABPu1japGd1aUBzFnA", "location": f"{university}"}
    response = requests.get(url, params=params)
    data = response.json()
    latlng = data["results"][0]["locations"][0]["latLng"]
    lat_data.append(latlng['lat'])
    long_data.append(latlng['lng'])
school_data["Latitude"] = pd.Series(lat_data)
school_data["Longitude"] = pd.Series(long_data)
school_data

,Name,Founding,Latitude,Longitude
0,"University of California, Berkeley",1869.0,37.87523,-122.24624
1,"University of California, Davis",1905.0,38.54430,-121.74617
2,"University of California, Irvine",1965.0,33.64252,-117.83679
3,"University of California, Los Angeles",1882.0,34.02773,-118.28110
4,"University of California, Riverside",1954.0,33.98099,-117.32349
...,...,...,...,...
142,Marymount California University,1932.0,33.98099,-117.32349
143,Mills College,1852.0,36.12265,-90.94003
144,National Hispanic University,1981.0,38.65650,-90.31027
145,Union Institute & University,1964.0,35.31243,-80.74272
146,"University of Northern California, Lorenzo Pat...",1983.0,38.89037,-77.03196

In [83]:
school_data[school_data["Latitude"].isna()]

Empty DataFrame
Columns: [Name, Founding, Latitude, Longitude]
Index: []

## Ethics

Instructions: Keep the contents of this cell. For each item on the checklist
-  put an X there if you've considered the item
-  IF THE ITEM IS RELEVANT place a short paragraph after the checklist item discussing the issue.
  
Items on this checklist are meant to provoke discussion among good-faith actors who take their ethical responsibilities seriously. Your teams will document these discussions and decisions for posterity using this section.  You don't have to solve these problems, you just have to acknowledge any potential harm no matter how unlikely.

Here is a [list of real world examples](https://deon.drivendata.org/examples/) for each item in the checklist that can refer to.

[![Deon badge](https://img.shields.io/badge/ethics%20checklist-deon-brightgreen.svg?style=popout-square)](http://deon.drivendata.org/)

### A. Data Collection
 - [X] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

> Example of how to use the checkbox, and also of how you can put in a short paragraph that discusses the way this checklist item affects your project.  Remove this paragraph and the X in the checkbox before you fill this out for your project

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?
 > We acknowledge that during the 1990 Census which the dataset is taken from, had undercounts of historically marginalized neighborhoods, and so will not attempt to extrapolate our results to current-day valuation. Other concerns with bias will be addressed after exploring our data further.
 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
 > There is no personally identifiable information in the dataset, as the data is on houses aggregated based on each geographical block. We will not try to identify individuals.
 - [ ] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

### B. Data Storage
 - [ ] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [ ] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [ ] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?
 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?
 >We recognize that our housing data is partially shaped by factors not fully captured in the dataset, such as redlining and racial segregation. These missing variables may confound calculated relationships.
 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
 >While our insights might be correct for the year 1990, we should not consider that these trends still apply today, as it has been over 30 years and a lot has changed. However, we will do our best to make accurate predictions with year 1990 data.
 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
 >We found a lot of public data from trustworthy sources online. There is no personally identifiable information in the dataset, and we will not try to identify individuals.
 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?
 >We will make sure that our data processing steps, distance calculations, and analyses will be documented and reproducible using Github version-controlled code.

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?
 >By controlling for median income, household age, and population density, we ensure that the difference in household prices is decided primarily by variables we want to account for, like nearby Universities and coastlines, while leaving out any association from the way neighborhoods with high minority populations have been historically marginalized.
 - [ ] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?
 >We will note that our insights are from the year 1990 so it may not generalize well to today, and also make it clear that our predictions may be affected by biases in the data mentioned earlier.

### E. Deployment
 - [ ] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [ ] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [ ] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

## Team Expectations

 - Communicate through our Discord server for calls/general project updates and the Instagram groupchat for urgent situations. Reasonable response time: within 24 hours. Virtual meetings will occur once a week (times are decided at the start of each week based on all members’ schedules). 

 - If a team member anticipates missing a deadline, they will inform the team as early as possible

 - Decisions will be made using unanimous votes. If conflicts arise, we will go with a majority vote.

 - Disagreements will be handled respectfully and constructively, with a focus on problem-solving.

## Project Timeline Proposal


| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 2/3  |  10 PM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; assign tasks for project proposal | 
| 2/17  |  10 pm |  Find all needed datasets, clean and pre-process | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part | 
| 2/18  | Before 11:59 PM  | Checkpoint #1 Data  | Turn in Checkpoint #1 Data |
| 2/24  | 10 PM  | Import & Wrangle Data | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 3/3  | 10 PM  | Finalize wrangling/EDA; Begin work on models | Discuss/edit models; Complete project check-in |
| 3/4  | Before 11:59 PM  | Checkpoint #2 EDA | Turn in Checkpoint #2 EDA |
| 3/10  | 10PM  | Complete models and most visualizations; Draft results/conclusion/discussion | Discuss/edit full project, discuss how to approach project video |
| 3/17  | Before 11:59 PM  | Final project notebook, video | Turn in Final Project & Group Project Surveys; do touchups as needed |